<!DOCTYPE html>
<html>
<head>
	<title>Error handling</title>
</head>
<body>
	<p>Please input a number between 5 and 10:</p>

	<input id="demo" type="text">
	<button type="button" onclick="myFunction()">Test Input</button>
	<p id="p01"></p>

	<input id="demo1" type="text">
	<button type="button" onclick="myFunction1()">Test Input</button>
	<p id="p1"></p>

	<script type="text/javascript">

   	/*The try statement lets you test a block of code for errors.

    The catch statement lets you handle the error.

    The throw statement lets you create custom errors.

    The finally statement lets you execute code, after try and catch, regardless of the result.
    
    Error object properties
    name: Sets or returns an error name
    message: Sets or returns an error message (a string)
    */
   
    
    try {
    	adddlert("Welcome Harish!");
    }
    catch(err) {
    	document.write(err.message);
    }

    function myFunction() {
    	var message, x;
    	message = document.getElementById("p01");
    	message.innerHTML = ""; //making it empty for every input 
    	x = document.getElementById("demo").value;
    	try {
    		if(x == "") throw "empty";
    		if(isNaN(x)) throw "not a number";
    		x = Number(x); //type conversion because input is a string 
    		if(x < 5) throw "too low";
    		if(x > 10) throw "too high";
    	}
    	catch(err) {
    		message.innerHTML = "Input is " + err;
    	}
    }

    function myFunction1() {
    	var message, x;
    	message = document.getElementById("p1");
    	message.innerHTML = ""; //making it empty for every input 
    	x = document.getElementById("demo1").value;
    	try {
    		if(x == "") throw "empty";
    		if(isNaN(x)) throw "not a number";
    		x = Number(x); //type conversion because input is a string 
    		if(x < 5) throw "too low";
    		if(x > 10) throw "too high";
    	}
    	catch(err) {
    		message.innerHTML = "Input is " + err;
    	}
    	finally {
    		document.getElementById("demo1").value = ""; // making the input box empty after irrespective of the errors
    	}
    }

    /*EvalError	An error has occurred in the eval() function. Newer versions of JavaScript do not throw EvalError. Use SyntaxError instead.
    RangeError	A number "out of range" has occurred
    ReferenceError	An illegal reference has occurred.if you use (reference) a variable that has not been declared
    SyntaxError	A syntax error has occurred
    TypeError	A type error has occurred
    URIError	An error in encodeURI() has occurred*/

    //For example: You cannot set the number of significant digits of a number to 500.

    var num = 1;
    try {
      num.toPrecision(500);  // A number cannot have 500 significant digits 
    }
    catch(err) {
      document.write(err.name + "</br>");
      document.write(err.message + "</br>");
    }

    var x;
    try {
      x = y + 1;  // y cannot be referenced (used) 
    }
    catch(err) {
      document.write(err.name + "</br>");
      document.write(err.message + "</br>");
    }

    try {
      eval("alert('Hello)");   // Missing ' will produce an error
    }
    catch(err) {
      document.write(err.name + "</br>");
      document.write(err.message + "</br>");
    }

    var num = 1;
    try {
      num.toUpperCase();   // You cannot convert a number to upper case
    }
    catch(err) {
      document.write(err.name + "</br>");
      document.write(err.message + "</br>");
    }
    
    //A URIError is thrown if you use illegal characters in a URI function:
    try {
        decodeURI("%%%");   // You cannot URI decode percent signs
    }
    catch(err) {
      document.write(err.name + "</br>");
      document.write(err.message + "</br>");
    }







   </script>

</body>
</html>